project:
  type: website

website:
  title: "Grupo de estudios sobre movilidad y desigualdad social"
  navbar:
    logo: "imagenes/logoblanco2020 sociales.png"
    right:
      - href: about.qmd
        text: Quiénes somos
      - icon: bi-envelope-at
        href: mailto:gedyms.iigg@gmail.com
      - icon: youtube
        href: https://www.youtube.com/@desigualdadymovilidadsocia3815
      - icon: github
        href: https://github.com/
format:
  html:
    theme: yeti
    css: styles.css

