project:
  type: website

website:
  title: "Grupo de estudios sobre movilidad y desigualdad social"
  navbar:
    logo: "imagenes/logoblanco2020 sociales.png"
    right:
      - href: about.qmd
        text: Quiénes somos
      - icon: bi-envelope-at
        href: mailto:gedyms.iigg@gmail.com
      - icon: youtube
        href: https://www.youtube.com/@desigualdadymovilidadsocia3815
      - icon: github
        href: https://github.com/joserodriguez86/web_equipo
        

format:
  html:
    toc: true
    toc-location: right
    theme: yeti
    css: styles.css
    bibliography: Mi biblioteca.bib
    csl: apa-no-ampersand.csl
  pdf:
    toc: true
    pdf-engine: xelatex
    bibliography: Mi biblioteca.bib
    csl: apa-no-ampersand.csl
    fig-format: png  
    fig-dpi: 300     
    fig-width: 8
    fig-height: 5
    reference-section-title: "Referencias"
    metadata:
      bibliography-heading-level: 1

